// Code generated by "stringer -type=UseCase"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Both-0]
	_ = x[Encoder-1]
	_ = x[Decoder-2]
}

const _UseCase_name = "BothEncoderDecoder"

var _UseCase_index = [...]uint8{0, 4, 11, 18}

func (i UseCase) String() string {
	if i < 0 || i >= UseCase(len(_UseCase_index)-1) {
		return "UseCase(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _UseCase_name[_UseCase_index[i]:_UseCase_index[i+1]]
}
