// Code generated by "encoder -type=Animalia"; DO NOT EDIT.
package creature

// GENERATED BY YO. DO NOT EDIT.

import (
	"bytes"
	"encoding/binary"

	"github.com/Intermernet/ebcdic"
	"github.com/t10471/converter/predefine"
)

type AnimaliaConverter struct {
	InfoConverter
	Name       [7]byte  `label:"名前"`
	Age        [2]byte  `label:"年齢"`
	ExtendArea [10]byte `label:"拡張エリア"`
}

func (cv *AnimaliaConverter) MarshalBuffer() (*bytes.Buffer, error) {
	buffer := new(bytes.Buffer)
	if err := binary.Write(buffer, binary.BigEndian, cv); err != nil {
		return nil, err
	}
	return buffer, nil
}
func (cv *AnimaliaConverter) UnmarshalBuffer(buffer *bytes.Buffer) error {
	if err := binary.Read(buffer, binary.BigEndian, cv); err != nil {
		return err
	}
	return nil
}
func (cv *AnimaliaConverter) ConvertFrom(original Animalia) error {
	var err error
	err = cv.InfoConverter.ConvertFrom(original.Info)
	if err != nil {
		return err
	}
	cv.Name = encodeAnimaliaEbcdic7(original.Name)
	cv.Age = encodeAnimaliaHex2(original.Age)
	cv.ExtendArea = encodeAnimaliaBlank10(original.ExtendArea)
	return nil
}
func (cv *AnimaliaConverter) ToOriginal() (Animalia, error) {
	var err error
	original := Animalia{}

	original.Info, err = cv.InfoConverter.ToOriginal()
	if err != nil {
		return Animalia{}, err
	}
	original.Name = decodeAnimaliaEbcdic7(cv.Name)
	original.Age = decodeAnimaliaHex2(cv.Age)
	original.ExtendArea = decodeAnimaliaBlank10(cv.ExtendArea)
	return original, nil
}
func encodeAnimaliaHex2(h predefine.Hex) [2]byte {
	v := predefine.Uint2bytes(uint64(h), 2)
	r := [2]byte{}
	copy(r[:], v)
	return r
}
func decodeAnimaliaHex2(b [2]byte) predefine.Hex {
	return predefine.Hex(predefine.Bytes2uint(b[:]))
}
func encodeAnimaliaBlank10(b predefine.Blank) [10]byte {
	r := [10]byte{}
	copy(r[:], bytes.Repeat([]byte{byte(0)}, int(b)))
	return r
}
func decodeAnimaliaBlank10(b [10]byte) predefine.Blank {
	return predefine.Blank(len(b))
}
func encodeAnimaliaEbcdic7(e predefine.Ebcdic) [7]byte {
	v := ebcdic.Encode([]byte(e))
	r := [7]byte{}
	copy(r[:], v)
	return r
}
func decodeAnimaliaEbcdic7(b [7]byte) predefine.Ebcdic {
	return predefine.Ebcdic(ebcdic.Decode(b[:]))
}
