// Code generated by "stringer -type=Detail"; DO NOT EDIT.

package creature

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DetailUnused-0]
	_ = x[DetailPlantaeRubiales-1]
	_ = x[DetailPlantaeOrchidales-2]
	_ = x[DetailAnimaliaMammals-3]
	_ = x[DetailAnimaliaAves-4]
}

const _Detail_name = "DetailUnusedDetailPlantaeRubialesDetailPlantaeOrchidalesDetailAnimaliaMammalsDetailAnimaliaAves"

var _Detail_index = [...]uint8{0, 12, 33, 56, 77, 95}

func (i Detail) String() string {
	if i < 0 || i >= Detail(len(_Detail_index)-1) {
		return "Detail(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Detail_name[_Detail_index[i]:_Detail_index[i+1]]
}
